name: testing_bloc_concept
description: Business Logic Concept in Our Mobile Application Development in Uganda

publish_to: 'none' # Remove this line if you wish to publish to


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc_test: ^9.0.1
  connectivity: ^3.0.6
  equatable: ^2.0.3
<<<<<<< HEAD

  connectivity_plus: "^2.0.2"

=======
  battery_plus: "^2.0.1"
  connectivity_plus: "^2.0.2"
  device_info_plus: "^3.1.0"
  network_info_plus: "^2.0.2"
  package_info_plus: "^1.3.0"
  sensors_plus: "^1.2.1"
  share_plus: "^3.0.4"
  android_alarm_manager_plus: "^2.0.3"
  android_intent_plus: "^3.0.2"
>>>>>>> b11ba8032322e814b0d32992a8057710ac2c47b2
  flutter:
    sdk: flutter
  #  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.12
flutter:
  uses-material-design: true
